# This is a basic workflow to help you get started with Actions

name: CI
env:
  deployutil: 'C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe'
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - run: |
         "& cd /c C:\inetpub\wwwroot && "C:\Program Files\json\pm2" status myapp2

#          "& cmd /c ${{ env.deployutil }} -verb:sync -source:runcommand -dest:runcommand='C:\\Program Files\\nodejs\\pm2.cmd restart QuotingSignup-qa',waitinterval=200000,wmsvc='https://remotehost:8172/msdeploy.axd?site=BackupSite',AuthType=Basic,userName=svc-BuildDeployDev,password='***' -allowUntrusted -verbose'"
#          "& cmd /c /"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe/" -verb:sync -source:runcommand -dest:runcommand=\"C:\\Program Files\\nodejs\\pm2.cmd restart QuotingSignup-qa\",waitinterval=200000,wmsvc='https://remotehost:8172/msdeploy.axd?site=BackupSite',AuthType=Basic,userName=svc-BuildDeployDev,password='***' -allowUntrusted -verbose'"
#          "& cmd /c /"C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe/""         
          
      - name: Setup nginx
        uses: cuchi/jinja2-action@v1.2.0
        with:
          template: infra/nginx.conf.j2
          output_file: infra/nginx.conf
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
